"""
Runs AI segmentation on an uploaded CT volume.

Input:
    storage/<study_id>/volume.npy
    storage/<study_id>/spacing.npy

Output:
    storage/<study_id>/mask.npy
"""

from pathlib import Path
import subprocess
import tempfile
import nibabel as nib    #Python library for reading and writing medical imaging files
import numpy as np

STORAGE = Path("storage")


class SegmentationService:

    def __init__(self, study_id: str):
        self.study_id = study_id
        self.study_dir = STORAGE / study_id

    def load_study(self):
        """Load CT volume and voxel spacing."""

        volume_path = self.study_dir / "volume.npy"
        spacing_path = self.study_dir / "spacing.npy"

        if not volume_path.exists():
            raise FileNotFoundError(
                f"No volume found for study '{self.study_id}'"
            )

        if not spacing_path.exists():
            raise FileNotFoundError(
                f"No spacing found for study '{self.study_id}'"
            )

        volume = np.load(volume_path)
        spacing = np.load(spacing_path)

        return volume, spacing

    def create_nifti(self, volume, spacing, output_path):
        """
        Convert NumPy volume into a NIfTI file.
        TotalSegmentator does not support .npy
        """

        affine = np.diag([
            float(spacing[0]),
            float(spacing[1]),
            float(spacing[2]),
            1.0                     #The last 1.0 is not another spacing value.
        ])                          #The last row/column are used for transformations

        image = nib.Nifti1Image(volume.astype(np.float32), affine)
        nib.save(image, output_path)

    def run_totalsegmentator(self, nifti_path, output_dir):
        """
        Run TotalSegmentator and segment only the spleen.
        """

        command = [
            "TotalSegmentator",
            "-i",
            str(nifti_path),
            "-o",
            str(output_dir),
            "--roi_subset",
            "spleen",
        ]

        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"TotalSegmentator failed:\n{result.stderr}"
            )

    def load_spleen_mask(self, output_dir):
        """
        Load spleen.nii.gz generated by TotalSegmentator.
        """

        spleen_file = output_dir / "spleen.nii.gz"

        if not spleen_file.exists():
            raise FileNotFoundError(
                "TotalSegmentator did not generate spleen.nii.gz"
            )

        image = nib.load(str(spleen_file))

        mask = image.get_fdata()           #This extracts the image data from the NIfTI object.
        print("Mask min:", mask.min())
        print("Mask max:", mask.max())
        print("Non-zero voxels:", np.count_nonzero(mask))
        
        mask = (mask > 0).astype(np.uint8) #stored as unsigned 8-bit integers

        return mask

    def save_mask(self, mask):

        np.save(self.study_dir / "mask.npy", mask)

    def segment(self):
        """
        Complete segmentation pipeline.

        Returns
        -------
        numpy.ndarray
            Binary spleen mask.
        """

        volume, spacing = self.load_study()

        with tempfile.TemporaryDirectory() as temp_dir:

            temp_dir = Path(temp_dir)

            nifti_path = temp_dir / "input.nii.gz"

            output_dir = temp_dir / "segmentations"

            output_dir.mkdir(exist_ok=True)

            self.create_nifti(
                volume,
                spacing,
                nifti_path,
            )

            self.run_totalsegmentator(
                nifti_path,
                output_dir,
            )

            print("\nFiles generated by TotalSegmentator:")
            for file in output_dir.iterdir():
                print(file.name)

            mask = self.load_spleen_mask(output_dir)

        self.save_mask(mask)

        return mask